### PR TITLE
Features/add county data

### PR DESCRIPTION
**Pull request by ghost**
Added county level data.

### CODE REVIEW

**Comment by connorrothschild** [comment]
Awesome! Do you think we need to create a unique key pair (state, county) so that a user can't select one county for multiple states (e.g. Harris county is a county in Texas and Georgia)

**Comment by Texas-Policy-Lab** [comment]
I want to try and get it filter the counties automatically. So If you select "Texas", then you only get the Texas counties. I'm not sure how to do that off the top of my head. I was going to tackle that question tomorrow. But if you have some time tonight and want to work on it, go for it!

**Comment by connorrothschild** [comment]
I'm going to work on features/add_timeline first but if I have time leftover I'll take a look!

**Comment by Texas-Policy-Lab** [comment]
Yep, I like it! Let's build it out!

**Comment by Texas-Policy-Lab** [comment]
It's not a perfect solution, it's a bit quirky. I wanted it to add the top counties whenever a user selected a new state, but currently you have to manually select the counties.

Do you think we should as "Dallas County, TX" instead of just "Dallas County" if more than one state is selected?

**Comment by connorrothschild** [comment]
Yeah it looks great! 

I think that would be a helpful addition in the event that a county name is present in multiple states.

**Pull request merged**
